RedpointGames/uet

- UET/uet/Commands/Internal/UpdateUPlugin/UpdateUPluginCommand.cs
- UET/uet/Services/DefaultPluginVersioning.cs
Turns out Fab doesn't actually support a single upload for multiple engine versions for code plugins, and we still need to submit (mostly identical) packages to them for each engine version.
> Restore engine-specific packaging for Fab

- .github/actions/upload-artifact/action.yml
- .github/workflows/test-publish.yml
- .github/workflows/uet.yml
This moves the test reporting step to a separate workflow that should, if my understanding of GitHub Actions is correct, work for pull requests submitted by external contributors.
> Try to fix permissions issue on uploading test results

- UET/uet/Commands/Internal/CreateGitHubRelease/DefaultReleaseUploader.cs
- UET/uet/Commands/Uefs/UefsInstallCommand.cs
- UET/uet/Commands/Upgrade/UpgradeCommandImplementation.cs
It turns out our strategy of having a `latest` tag that gets updated with new files on every release is unnecessary. GitHub provides a slightly different URL that we can use to get `package.version` from the newest release anyway:
```bash
https://github.com/RedpointGames/uet/releases/download/latest/package.version
https://github.com/RedpointGames/uet/releases/latest/download/package.version
```
The URLs are very similar, so I suspect the original strategy came about because I thought that `latest/download` didn't work any more.
> Use GitHub magic 'latest' URL instead of updating a 'latest' tag

- UET/Redpoint.Uet.BuildPipeline.Providers.Test/Plugin/Custom/CustomPluginTestProvider.cs
- UET/Redpoint.Uet.BuildPipeline.Tests/BuildGraphGeneratorTests.cs
- UET/Redpoint.Uet.BuildPipeline.Tests/DynamicBuildGraphIncludeTests.cs
- UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Plugin.xml
- UET/Redpoint.Uet.BuildPipeline/BuildGraph/Dynamic/DefaultDynamicBuildGraphIncludeWriter.cs
- UET/Redpoint.Uet.BuildPipeline/BuildGraph/Dynamic/IDynamicBuildGraphIncludeWriter.cs
- UET/Redpoint.Uet.Configuration/BuildConfigSourceGenerationContext.cs
- UET/Redpoint.Uet.Configuration/Dynamic/BuildConfigDynamic.cs
- UET/Redpoint.Uet.Configuration/Dynamic/BuildConfigDynamicConverter.cs
- UET/Redpoint.Uet.Configuration/Dynamic/BuildConfigDynamicConverterHelpers.cs
- UET/Redpoint.Uet.Configuration/Dynamic/BuildConfigPredefinedDynamic.cs
- UET/Redpoint.Uet.Configuration/Dynamic/BuildConfigPredefinedDynamicConverter.cs
- UET/Redpoint.Uet.Configuration/Dynamic/BuildConfigTestPredefinedConverter.cs
- UET/Redpoint.Uet.Configuration/Plugin/BuildConfigPlugin.cs
- UET/Redpoint.Uet.Configuration/Plugin/BuildConfigPluginPredefinedTestDependencies.cs
- UET/uet/Commands/Build/BuildCommand.cs
- UET/uet/Commands/Build/DefaultBuildSpecificationGenerator.cs
- UET/uet/Commands/Build/IBuildSpecificationGenerator.cs
- UET/uet/Commands/Internal/GenerateJsonSchema/DefaultJsonSchemaGenerator.cs
- UET/uet/Commands/Test/TestCommand.cs
This adds support for "predefined" tests in `BuildConfig.json` files for plugins:
```jsonc
{
"Type": "Plugin",
"Tests": [
{
"Name": "Test Name",
"ShortName": "tn",
"Type": "Custom",
"Custom": {
// ...
},
"Dependencies": {
"Package": {
// Same as "Package" in distributions...
},
"Build": {
// Same as "Build" in distributions...
}
}
}
],
"Distributions": [
{
"Name": "Distribution",
// ...
"Tests": [
{
"Name": "License Key Validation",
"Type": "Predefined",
"Predefined": "License Key Validation"
}
]
}
]
}
```
Predefined tests can be used in two ways:
- Referenced in the `Tests` array for a distribution, by setting `Type` to "Predefined" and `Predefined` to the name of the predefined test. If you're using the same test in multiple distributions, this reduces the amount of …
> Add support for predefining tests and using them in `uet test`

- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/Custom/BuildConfigProjectDeploymentCustom.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/Custom/CustomProjectDeploymentProvider.cs
Hey June,
I looked into implementing the custom project deployment provider. 
I implemented it similar to the custom project test provider, which is to just grab all binaries and invoke the script once.
Do you think this implementation makes sense, or would you rather have something like the Steam provider where you invoke the script for a specific target?
> Implement custom deployment provider

- UET/Redpoint.SelfVersion/RedpointSelfVersion.cs
- UET/Redpoint.Uet.SdkManagement/Sdk/MacSdkSetup.cs
- UET/uet/Commands/Internal/UpdateUPlugin/UpdateUPluginCommand.cs
- MacSdkSetup.cs: error IDE0120: Simplify LINQ expression
- RedpointSelfVersion.cs: error IDE0280: Use 'nameof'
- UpdateUPluginCommand.cs: error CA1853: Do not guard 'Dictionary.Remove(key)' with 'Dictionary.ContainsKey(key)'
> Fix code analyzer errors that haven't been silenced.

- UET/Redpoint.PathResolution/DefaultPathResolver.cs
If the PATH variable changes during the execution of UET (such as a program being installed and adding itself to the PATH), this ensures that the path resolver can find the new binaries.
> Fallback to user and machine PATH variables

- UET/Redpoint.Uet.BuildPipeline.Executors.GitLab/GitLabBuildExecutor.cs
This will make GitLab cancel jobs when they are no longer relevant (such as a new commit being pushed to a merge request).
> Mark GitLab jobs as interruptable

- UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Project.xml
The -distribution flag is necessary for code signing to sign with the release keys instead of debug keys.
cc @JasperDeLaat94 This one *might* affect you; I'm not sure how `-distribution` interacts with APK builds distributed outside of the store. Let me know if we need to make this a configurable option.
> Set -distribution flag when Android/IOS is being built in Shipping configuration

- UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Project.xml
This makes Android stage/package to the normal directory name when no specific cook flavor is requested.
> Fix Android build/stage when no cook flavor is specified

- UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Project.xml
This makes it much easier to understand what is going on in the project build, and allows us in future to support listing specific variants in BuildConfig.json instead of just matrixes.
> Move project compile/cook/package into macros

- UET/Redpoint.Uet.BuildPipeline.Executors.GitLab/GitLabBuildExecutorFactory.cs
- UET/Redpoint.Uet.BuildPipeline.Executors.GitLab/GitLabBuildNodeExecutor.cs
- UET/Redpoint.Uet.BuildPipeline.Executors.Local/LocalBuildExecutor.cs
- UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Project.xml
- UET/Redpoint.Uet.BuildPipeline/BuildGraph/PreBuild/DefaultPreBuild.cs
- UET/Redpoint.Uet.BuildPipeline/BuildGraph/PreBuild/IPreBuild.cs
- UET/Redpoint.Uet.BuildPipeline/BuildPipelineServiceExtensions.cs
This allows you to have one project that targets multiple Android stores. Android compilation and cook will happen once (per existing matrix behaviour), while multiple packaging jobs will be emitted, each with different flags to BuildCookRun for the way that platform requires APK/AAB packaging to be done.
These target platform names are optional - you can continue to use "Android" instead in which case the project settings are used as-is.
For example, the `Build` section can now be specified as:
``` json
{
"Build": {
"Editor": {
"Target": "ExampleOSSEditor"
},
"Game": {
"Targets": [
"ExampleOSS"
],
"Platforms": [
"MetaQuest",
"GooglePlay"
],
"Configurations": [
"Shipping"
]
}
}
}
```
> Support "MetaQuest" and "GooglePlay" as target platform names

- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/DeploymentProviderRuntimeJson.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/DeploymentProviderServiceCollections.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/DeploymentProviderSourceGenerationContext.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/Meta/BuildConfigProjectDeploymentMeta.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/Meta/MetaProjectDeploymentProvider.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/Package/BuildConfigProjectDeploymentPackage.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Redpoint.Uet.BuildPipeline.Providers.Deployment.csproj
This adds support for deploying Meta Quest builds as a `Deployment` step:
```json
"Deployment": [
{
"Name": "Meta Quest",
"Type": "Meta",
"Manual": false,
"Meta": {
"AppID": "12345...",
"AppSecretEnvVar": "META_QUEST_APP_SECRET",
"Channel": "ALPHA",
"Package": {
"Type": "Game",
"Target": "TargetName",
"Platform": "MetaQuest",
"Configuration": "Shipping"
}
}
}
]
```
> Add Meta Quest deployment support

- UET/Redpoint.Uet.BuildPipeline/BuildGraph/PreBuild/DefaultPreBuild.cs
This cleans just the Android folder under Binaries and StagedBuilds when building for Android (in addition to the existing clean rules we have for MetaQuest and GooglePlay). This prevents stale build files from being tagged during Android builds.
This should fix the "stale files being tagged" issue that was mentioned in #82.
> Ensure Binaries and StagedBuilds folder for Android gets cleaned pre-build

- UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Project.xml
This fixes up Android project builds distributed through BuildGraph when the project contains a plugin with UPL files.
> Run reparent-additional-properties-in-targets for Pak and Stage in project builds

- .github/workflows/wine-container.yml
This is mostly an experiment; it builds a Docker container with patched Wine for Unreal Engine using the scripts in https://github.com/EpicGamesExt/WineResources, with no additional modifications on our end (except changing the tag). The Docker container is then published as a package under the UET repository so that we can potentially use it in future as a well known tag for build automation.
> Build Wine container for Unreal Engine

- UET/Redpoint.Uba/DefaultUbaServer.cs
- UET/Redpoint.Uba/DefaultUbaServerFactory.cs
- UET/Redpoint.Uba/IUbaServer.cs
- UET/Redpoint.Uba/UbaLoggerForwarder.cs
- UET/Redpoint.Uba/UbaProcessDescriptor.cs
- UET/Redpoint.Uba/UbaProcessSpecification.cs
- UET/Redpoint.Uet.BuildPipeline.Executors.GitLab/Redpoint.Uet.BuildPipeline.Executors.GitLab.csproj
- UET/uet/Commands/CMake/CMakeCommand.cs
- UET/uet/Commands/Internal/CMakeUbaRun/CMakeUbaRunCommand.cs
- UET/uet/Commands/Internal/CMakeUbaServer/CMakeUba.proto
- UET/uet/Commands/Internal/CMakeUbaServer/CMakeUbaServerCommand.cs
- UET/uet/Commands/Internal/CMakeUbaServer/KubernetesConstants.cs
- UET/uet/Commands/Internal/CMakeUbaServer/KubernetesNodeState.cs
- UET/uet/Commands/Internal/CMakeUbaServer/KubernetesNodeWorker.cs
- UET/uet/Commands/Internal/CMakeUbaServer/UbaCoordinatorKubernetes.cs
- UET/uet/Commands/Internal/CMakeUbaServer/UbaCoordinatorKubernetesConfig.cs
- UET/uet/Commands/Internal/InternalCommand.cs
- UET/uet/Commands/ParameterSpec/EngineSpec.cs
- UET/uet/Program.cs
- UET/uet/uet.csproj
This adds a `uet cmake` command which can be used to distribute CMake-based builds with the Unreal Build Accelerator and Kubernetes. This is mostly useful to rapidly build the Clang compiler.
Running `uet cmake --help` will also give you the "how to use it" information described below.
Before you can distribute builds, you must configure your BuildConfiguration.xml file located at `%appdata%\Unreal Engine\UnrealBuildTool\BuildConfiguration.xml` with the settings to connect to the Kubernetes cluster. The Kubernetes cluster must have Windows nodes in it. You can use RKM (https://src.redpoint.games/redpointgames/rkm) to spin up a Kubernetes cluster with Windows nodes with a single command.
```xml
<?xml version="1.0" encoding="utf-8"?>
<Configuration …
```
> Add 'uet cmake' command to distribute CMake-based builds over UBA

- UET/Redpoint.Uet.BuildPipeline/BuildGraph/Patching/DefaultBuildGraphPatcher.cs
If we're using a source-based engine, RunUAT will already rebuild UBT and associated binaries if they're out-of-date when we start BuildGraph.
> Skip rebuilding UBT when using a source-based engine

- .gitattributes
Users that have configured `core.autocrlf=true` will check out the project with `crlf` line endings. This causes inconsistencies in the working tree because `.editorconfig` specifies new line ending should be `lf`.
Given the project is almost entirely encoded with `lf` and the editorconfig file, it makes sense to force this during checkout as well. This change overrides the user's preference locally and ensures line endings are consistent in the working tree.
> Force `lf` line endings.

- UET/uet/Commands/Config/ConfigCommand.cs
- UET/uet/Commands/ParameterSpec/PathSpec.cs
- UET/uet/Commands/Run/RunCommand.cs
- UET/uet/Program.cs
This adds a `uet run` command that runs the editor, game or related tool such as UAT or UBT. This is primarily useful so you don't have to remember the exact path to tools such as UAT.
The 'target' argument specifies what to run, and it can be any of the following:
```
editor:         Run the Unreal Engine editor.
editor-cmd:     Run the Unreal Engine editor as a command-line application.
game:           Run the Unreal Engine game for this project on the current platform. This uses 
the editor binary to quickly launch the game. This can only be used in a project context.
uat:            Run UnrealAutomationTool.
ubt:            Run UnrealBuildTool.
uba-visualizer: Run the Unreal Build Accelerator visualizer.
```
If `--path` points to a project file, the target will automatically receive …
> Add `uet run` command

- UET/Redpoint.CloudFramework.Abstractions/IWebAppProvider.cs
- UET/Redpoint.CloudFramework.Abstractions/Redpoint.CloudFramework.Abstractions.csproj
- UET/Redpoint.CloudFramework.CLI/GenerateOpenApiJson.cs
- UET/Redpoint.CloudFramework.CLI/Redpoint.CloudFramework.CLI.csproj
- UET/Redpoint.CloudFramework/Redpoint.CloudFramework.csproj
- UET/Redpoint.CloudFramework/Startup/DefaultWebAppConfigurator.cs
- UET/Redpoint.CloudFramework/Startup/IWebAppConfigurator.cs
- UET/UET.sln
So that downstream projects only need to consume Redpoint.CloudFramework to get the analyzer and tooling
> Make Redpoint.CloudFramework depend on analyzer + CLI in NuGet package

- UET/Lib/Executable.Build.props
This bug is reportedly fixed in .NET 9 and this flag should make UET start up faster on macOS.
> Enable PublishReadyToRun on macOS again

- UET/Redpoint.Uet.SdkManagement/Redpoint.Uet.SdkManagement.csproj
I tried using the VS profiler to see exactly what analyzer was causing this, but the only detail I could see is some kind of "data flow" analysis.
> Fix slow build caused by analyzers on Redpoint.Uet.SdkManagement

- UET/uet.shim/Program.cs
Builds of UET now include the Git commit as part of the 'ProductVersion' that gets embedded into the binary. This strips off the commit part (after the + character if present) so that the retrieved version number matches the format that UET expects.
> Fix UET shim reading product version of current UET binary

- UET/uet.shim/Program.cs
- UET/uet/Commands/Upgrade/UpgradeCommand.cs
Rather than failing immediately, use exponential backoff when GitHub returns 504 (Gateway Timeout)
> Use exponential backoff for UET shim and 'uet upgrade' commands when GitHub is down

- UET/uet/Commands/Format/FormatCommand.cs
clang-format's "FixNamespaceComments" setting does not behave correctly if the namespace is longer than the line character limit. Turn this setting off by default.
> Set FixNamespaceComments to false by default

- UET/uet/Commands/Format/FormatCommand.cs
The code auto-fix for CA1822 makes methods static when it thinks they can be. It does the wrong thing for platform extensions because it can't see where methods are implementing interface members.
> Skip CA1822 fix on 'uet format'

- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/Custom/BuildConfigProjectDeploymentCustom.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/Custom/CustomProjectDeploymentProvider.cs
Implemented based on your suggestion to use `BuildConfigProjectDeploymentPackage`, but implemented as an array so you can choose to require multiple packages (e.g. Client + Server builds) and deploy them together (e.g. zip up and archive to shared storage).
resolves #167
> Add support for requiring packages in custom project deployment provider.

- UET/Redpoint.Uet.BuildPipeline.Tests/BuildGraphGeneratorTests.cs
- UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Plugin.xml
- UET/Redpoint.Uet.Configuration/Plugin/BuildConfigPluginBuild.cs
- UET/Redpoint.Uet.SdkManagement/Sdk/WindowsSdk/WindowsSdkInstaller.cs
- UET/Redpoint.Uet.SdkManagement/Sdk/WindowsSdkSetup.cs
- UET/uet/Commands/Build/DefaultBuildSpecificationGenerator.cs
This also updates the Windows SDK installation to download and install PDBCopy automatically, which is necessary for symbol removal.
> Add "StripDebugSymbols" options to plugin builds

- UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Project.xml
Reverts RedpointGames/uet#176
This change breaks builds for installed engines:
```
[Compile UnrealEditor Win64] Couldn't find target rules file for target 'UnrealPak' in rules assembly 'UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
```
We'll need better heuristics around when to compile `UnrealPak` in the BuildGraph script.
> Revert "Fix "Pak and Stage" missing UnrealPak for source-based engines"

- UET/Redpoint.Uet.BuildPipeline.Executors.BuildServer/BuildJobJson.cs
- UET/Redpoint.Uet.BuildPipeline.Executors.BuildServer/BuildServerBuildExecutor.cs
- UET/Redpoint.Uet.BuildPipeline.Executors.GitLab/GitLabBuildNodeExecutor.cs
- UET/Redpoint.Uet.BuildPipeline.Executors.Local/LocalBuildExecutor.cs
- UET/Redpoint.Uet.BuildPipeline/Executors/BuildEngineSpecification.cs
- UET/Redpoint.Uet.BuildPipeline/Executors/Engine/DefaultEngineWorkspaceProvider.cs
- UET/Redpoint.Uet.Configuration/Engine/BuildConfigEngineDistribution.cs
- UET/Redpoint.Uet.Configuration/Engine/BuildConfigEngineExternalSource.cs
- UET/Redpoint.Uet.Workspace/PhysicalGit/DefaultPhysicalGitCheckout.cs
- UET/Redpoint.Uet.Workspace/PhysicalGit/GitExecutionContext.cs
- UET/uet/Commands/ParameterSpec/EngineSpec.cs
- UET/uet/Commands/ParameterSpec/EngineSpecType.cs
The "Source" property of engine distributions has been renamed to "ExternalSource", and you can now place a BuildConfig.json file in the repository root containing an engine to do an installed engine build.
> Support BuildConfig.json in the same directory as an engine for engine builds

- UET/Redpoint.Uet.BuildPipeline.Tests/BuildGraphGeneratorTests.cs
- UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Plugin.xml
- UET/Redpoint.Uet.Configuration/Plugin/BuildConfigPluginBuild.cs
- UET/uet/Commands/Build/DefaultBuildSpecificationGenerator.cs
This can reduce compilation times for plugin builds when you don't need the legacy Intel architecture.
> Allow turning off Intel plugin builds for macOS

- UET/Redpoint.Uet.BuildPipeline.Tests/BuildGraphGeneratorTests.cs
- UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Project.xml
- UET/Redpoint.Uet.BuildPipeline/BuildGraph/DefaultBuildGraphArgumentGenerator.cs
- UET/uet/Commands/Build/DefaultBuildSpecificationGenerator.cs
This is another go at #176, this time with proper detection of whether or not the Unreal Engine being built against has already been made into an "installed build" (and thus can't have engine-level targets built).
This also builds "BootstrapPackagedGame" in addition to "UnrealPak", which should fix the missing entry point on packaged Windows builds.
> Build UnrealPak and BootstrapPackagedGame when projects are built with source engine

- UET/uet/Commands/Internal/EnginePerforceToGit/EnginePerforceToGitCommand.cs
This should fix the "Failed to copy: open ... is a directory" error during sync.
> Add --delete-before for rclone call

- UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Project.xml
In order for it to be included in packaged games, even if the packaged game is not built for Shipping.
> BootstrapPackagedGame must be built in Shipping configuration

- UET/Redpoint.Windows.HostNetworkingService.Tests/HnsTests.cs
- UET/Redpoint.Windows.HostNetworkingService.Tests/Redpoint.Windows.HostNetworkingService.Tests.csproj
- UET/Redpoint.Windows.HostNetworkingService/ComWrapper/ClassIds.cs
- UET/Redpoint.Windows.HostNetworkingService/ComWrapper/IHNSApi.cs
- UET/Redpoint.Windows.HostNetworkingService/ComWrapper/Ole32.cs
- UET/Redpoint.Windows.HostNetworkingService/DefaultHns.cs
- UET/Redpoint.Windows.HostNetworkingService/HnsEndpoint.cs
- UET/Redpoint.Windows.HostNetworkingService/HnsEndpointWithId.cs
- UET/Redpoint.Windows.HostNetworkingService/HnsJsonSerializerContext.cs
- UET/Redpoint.Windows.HostNetworkingService/HnsNetwork.cs
- UET/Redpoint.Windows.HostNetworkingService/HnsNetworkWithId.cs
- UET/Redpoint.Windows.HostNetworkingService/HnsNotAvailableException.cs
- UET/Redpoint.Windows.HostNetworkingService/HnsPolicyList.cs
- UET/Redpoint.Windows.HostNetworkingService/HnsPolicyListWithId.cs
- UET/Redpoint.Windows.HostNetworkingService/HnsResponse.cs
- UET/Redpoint.Windows.HostNetworkingService/HnsSubnet.cs
- UET/Redpoint.Windows.HostNetworkingService/HnsSubnetPolicy.cs
- UET/Redpoint.Windows.HostNetworkingService/IHnsApi.cs
- UET/Redpoint.Windows.HostNetworkingService/README.md
- UET/Redpoint.Windows.HostNetworkingService/Redpoint.Windows.HostNetworkingService.csproj
- UET/UET.sln
This provides a managed library on top of the [HNS API](https://learn.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture#container-network-management-with-host-network-service) for managing container networks on Windows. It connects to the COM object exposed by Windows Containers, while still being compatible with trimming and AOT, which is necessary for UET.
> Implement Redpoint.Windows.HostNetworkingService library

- UET/uet/Commands/Internal/RkmService/RkmServiceCommand.cs
- UET/uet/Commands/Upgrade/UpgradeCommand.cs
- UET/uet/Commands/Upgrade/UpgradeCommandImplementation.cs
This ensures RKM is always running the latest version when it starts up, which helps clusters recover faster if we ship an update that breaks RKM.
> Automatically upgrade UET on RKM start, and restart service if necessary

- UET/Redpoint.KubernetesManager/Services/DefaultKubernetesClientFactory.cs
I'm hoping that Version.GetCodeAsync is just special cased in some way that breaks it's usage in AOT scenarios, because I can't otherwise see why this would fail as it does.
> Try using CoreV1.ListNamespaceAsync instead of Version.GetCodeAsync

- UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Plugin.xml
This explicitly turns off these plugins when assembling test projects for plugins in 5.6 and later.
> Prevent Fab and OnlineSubsystemEOS plugins from being enabled by default

- UET/Redpoint.Uet.BuildPipeline.Executors.GitLab/GitLabBuildNodeExecutor.cs
- UET/Redpoint.Uet.BuildPipeline.Executors.Jenkins/JenkinsBuildNodeExecutor.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Prepare/Project/DownloadPlugin/DownloadPluginProjectPrepareProvider.cs
- UET/Redpoint.Uet.BuildPipeline/Executors/Engine/DefaultEngineWorkspaceProvider.cs
- UET/Redpoint.Uet.Workspace.Tests/PhysicalGitCheckoutTests.cs
- UET/Redpoint.Uet.Workspace/DefaultWorkspaceProvider.cs
- UET/Redpoint.Uet.Workspace/Descriptors/GitWorkspaceDescriptor.cs
- UET/uet/Commands/Internal/EngineCheckout/EngineCheckoutCommand.cs
When this environment variable is set to '1' on the build server, UET will reuse workspaces where the Git branch or merge request ID is the same, instead of only reusing workspaces where the Git commit is the same.
> Add experimental UET_USE_LESS_UNIQUE_RESERVATION_NAMES_FOR_GIT option

- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/DeploymentProviderRuntimeJson.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/DeploymentProviderServiceCollections.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/DeploymentProviderSourceGenerationContext.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/GooglePlay/BuildConfigProjectDeploymentGooglePlay.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/GooglePlay/GooglePlayProjectDeploymentProvider.cs
- UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Redpoint.Uet.BuildPipeline.Providers.Deployment.csproj
- UET/uet/Commands/Run/RunCommand.cs
It can be used like this in the deployments section:
```json
{
"Name": "Google Play",
"Type": "GooglePlay",
"GooglePlay": {
"Tracks": ["internal", "alpha"],
"JsonKeyPath": "path/to/json/file",
"PackageName": "games.redpoint.MinuteOfMayhem",
"Package": {
"Configuration": "Shipping",
"Platform": "GooglePlay",
"Target": "MinuteOfMayhem",
"Type": "Game"
}
}
}
```
Instead of setting `JsonKeyPath`, you can set the environment variable `UET_GOOGLE_PLAY_JSON_KEY_PATH` if you want this value provided by a build server.
> Support Google Play deployment with Fastlane

- UET/Redpoint.Uet.BuildPipeline/BuildGraph/Patching/BuildGraphPatches.json
- UET/Redpoint.Uet.BuildPipeline/BuildGraph/Patching/IBuildGraphPatcher.cs
- UET/uet/Commands/Internal/InternalCommand.cs
- UET/uet/Commands/Internal/Patch/PatchCommand.cs
This should fix CVE warnings when building against 5.6
> Patch Magick.NET-Q16-HDRI-AnyCPU package reference

- UET/uet/Commands/Cluster/ClusterRunKubeletCommand.cs
To reduce the number of kubelet process restarts.
> Make Kubelet service wait until a containerd process is running

- UET/Lib/Helm/rkm/templates/dockerd-windows/dockerd.yaml
This fixes a CrashLoopBackoff scenario where dockerd detects an old daemon and won't start.
> Terminate existing dockerd process before starting dockerd container

- UET/Redpoint.ProcessExecution.Tests/Redpoint.ProcessExecution.Tests.csproj
- UET/Redpoint.ProcessExecution.Tests/TrustedInstallerTests.cs
- UET/Redpoint.ProcessExecution/NativeMethods.txt
- UET/Redpoint.ProcessExecution/ProcessExecutionServiceExtensions.cs
- UET/Redpoint.ProcessExecution/ProcessSpecification.cs
- UET/Redpoint.ProcessExecution/Windows/Ntdll/NtdllPInvoke.cs
- UET/Redpoint.ProcessExecution/Windows/RunAsTrustedInstallerFailedException.cs
- UET/Redpoint.ProcessExecution/Windows/WindowsProcessExecutor.cs
- UET/Redpoint.ProcessExecution/Windows/WindowsTrustedInstaller.cs
This is to support RKM automatically applying the `vfp_forward` patch to the registry when needed.
> Add RunAsTrustedInstaller to ProcessExecutor library

- UET/Redpoint.Uet.Workspace/PhysicalGit/DefaultPhysicalGitCheckout.cs
'git checkout' operations are now reliant on network connectivity due to the use of `--filter=tree:0`. Therefore we need to invoke them using the fault tolerant function.
> Make 'git checkout' fault tolerant

- UET/Redpoint.Uet.BuildPipeline.Executors.GitLab/GitLabBuildExecutor.cs
- UET/Redpoint.Uet.BuildPipeline.Executors.GitLab/GitLabBuildNodeExecutor.cs
- UET/Redpoint.Uet.BuildPipeline/Executors/BuildEngineSpecification.cs
This optimizes workspace allocation on GitLab when the engine being used doesn't support or allow concurrency.
It also adds a new environment variable `UET_USE_EXCLUSIVE_NODES_FOR_NONCONCURRENT_ENGINE` which will request tags 'buildgraph-exclusive-windows' and 'buildgraph-exclusive-mac' (GitLab runners with this tag should be configured to only run one job at a time per node). This ensures that our concurrent GitLab runners don't idle waiting for an engine or target workspace to unlock due to non-concurrency.
> Request non-concurrent target workspace if engine is non-concurrent

- UET/Redpoint.Uet.Workspace/PhysicalGit/DefaultPhysicalGitCheckout.cs
- UET/Redpoint.Uet.Workspace/Redpoint.Uet.Workspace.csproj
- UET/uet/Commands/Internal/RegisterGitLabRunner/RegisterGitLabRunnerCommand.cs
On Windows, if running with Administrator permissions, we'll check if an existing process has the index.lock file open (in case there is a Git process running in the background that is unsafe to terminate). Otherwise, we just delete it.
> Remove existing index.lock files when updating Git repositories

- UET/Redpoint.Uet.BuildPipeline/BuildGraph/DefaultBuildGraphExecutor.cs
- UET/Redpoint.Uet.BuildPipeline/BuildGraph/IBuildGraphExecutor.cs
In order to get editor binaries to be correctly staged to shared storage when building a project with a source-based engine, we need to symbolically link the target workspace into the engine workspace, and set the engine workspace as the BuildGraph project root.
> Symbolically link target workspace into engine for builds with source engines

- UET/uet/Commands/Internal/RemoveStalePrecompiledHeaders/RemoveStalePrecompiledHeadersCommand.cs
To diagnose an issue where PCH files were deleted after an immediate build retry.
> Log engine path change for stale PCH detection

- UET/Redpoint.Uet.Uat/DefaultUATExecutor.cs
Trying to track down why automatic retries aren't clearing out the local BuildGraph cache.
> Add more diagnostics around retry behaviour
