UET/Redpoint.Uet.Workspace/PhysicalGit/DefaultPhysicalGitCheckout.cs
This automatically upgrades Git to the latest version via WinGet or Homebrew if possible.
=> Automatically upgrade Git before using it

UET/Redpoint.Uet.SdkManagement/Sdk/MacSdkSetup.cs
The newer versions of Xcode require iOS to be installed separately. This updates the Mac SDK management to run those initial commands.
=> Install iOS platform with xcodebuild for Mac SDK

UET/Redpoint.Uet.SdkManagement/Sdk/AndroidSdkSetup.cs
This environment variable overrides what JDK version is used for the Android platform. Currently supports values "11" and "17" (the default). Resolves #54.
=> Add UET_OVERRIDE_JDK_VERSION environment variable

UET/Redpoint.Uet.BuildPipeline.Tests/BuildGraphGeneratorTests.cs, UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Project.xml, UET/uet/Commands/Build/DefaultBuildSpecificationGenerator.cs
Fixes #27.
cc @JasperDeLaat94 I don't think this change should affect you since the setting only applies to the Google Play store section of config, but let me know if it does.
=> Set Android StoreVersion to UNIX timestamp

UET/Redpoint.Uet.BuildPipeline/BuildGraph/BuildGraph_Project.xml
Attempt to fix #82 (at least the debug symbols side of things).
=> Set StoreVersion when executing Compile step for Android

UET/BuildTrimmedLocally.ps1, UET/Redpoint.Uba/DefaultUbaServer.cs, UET/uet/Commands/Internal/CreateGitHubRelease/DefaultReleaseUploader.cs
=> Use GC.KeepAlive to prevent the exited lambda from being GC'd

.github/workflows/uet.yml, UET/Redpoint.CloudFramework/Models/IModel.cs, UET/Redpoint.CloudFramework/Models/Model.cs, UET/UET.sln
We still require access to this for some legacy code.
=> Make IModel.GetTypes() public for now

.github/workflows/cf-containers.yml, UET/Lib/Container/cf-sdk.Dockerfile
These container images are the .NET SDK image, with Node.js added.
=> Publish SDK container for Cloud Framework

UET/Redpoint.Uefs.Package.SparseImage/SparseImagePackageMounter.cs, UET/Redpoint.Uefs.Package.Vhd/VhdPackageMounter.cs
Also, embed hash of package path and last write time of package file into the shadow path filename.
=> Auto-delete shadow path and retry UEFS mount on macOS

UET/uet/Commands/Internal/EnginePerforceToGit/EnginePerforceToGitCommand.cs, UET/uet/Commands/Internal/InternalCommand.cs
This command can be used to periodically sync the Epic Games Perforce repository for Unreal Engine into a Git repository.
=> Add internal 'engine-perforce-to-git' command

UET/uet/Commands/Internal/GenerateJsonSchema/DefaultJsonSchemaGenerator.cs
=> Fix schema generation for dynamic types

UET/uet/Commands/Run/RunCommand.cs
This makes it easier to run ADB when it's been installed via the automatic SDK management.
=> Add support for 'uet run adb' for Android development

UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/Custom/BuildConfigProjectDeploymentCustom.cs, UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/Custom/CustomProjectDeploymentProvider.cs
Similar idea to custom prepare scripts.
=> Add script argument support to custom project deployment.

UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/Docker/BuildConfigProjectDeploymentDocker.cs, UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/Docker/BuildConfigProjectDeploymentDockerHelm.cs, UET/Redpoint.Uet.BuildPipeline.Providers.Deployment/Project/Docker/DockerProjectDeploymentProvider.cs
This effectively allows you to deploy Agones fleets directly from UET.
=> Support deploying Helm charts from Docker deployment

UET/Lib/LibraryPackaging.Build.props, UET/uet/Commands/Build/BuildCommand.cs
=> Fix scenario where --test or --deploy are omitted entirely

UET/uet/Commands/Build/BuildCommand.cs
Do not log executor-git-url's contents as it likely contains a secret.
Whoops..
Ready for merge
=> Fix credential leak in executor-git-branch

UET/Redpoint.Uet.SdkManagement/Sdk/MacSdkSetup.cs, UET/uet/Commands/Internal/InstallXcode/InstallXcodeCommand.cs, UET/uet/Commands/Internal/InternalCommand.cs
This can be used like so: `uet internal install-xcode --version 15.4`, provided that you've downloaded Xcode 15.4 and set it up as per the SDK management requirements.
=> Add command for manually installing a specific Xcode version

UET/Lib/Framework.Build.props, UET/Redpoint.ProgressMonitor/Redpoint.ProgressMonitor.csproj
Fixes Rider failing to restore project.
=> Remove net48 support from ProgressMonitor

UET/uet/Commands/Run/RunCommand.cs
UET always sets the DEVELOPER_DIR back to the command-line tools when it runs, so we have to use the local SDK manager to set up the Xcode path when using `uet run`, otherwise Unreal Editor can't locate Xcode.
=> Set up environment for Xcode for 'uet run'

UET/Redpoint.KubernetesManager/Components/KubeProxyComponent.cs, UET/Redpoint.KubernetesManager/Redpoint.KubernetesManager.csproj
=> Automatically install the conntrack package

UET/uet/Commands/Cluster/DefaultRkmClusterControl.cs, UET/uet/Commands/Internal/RkmService/RkmServiceCommand.cs, UET/uet/Services/DefaultSelfLocation.cs, UET/uet/Services/ISelfLocation.cs
This fixes automatic upgrades to work properly.
=> Use a version independent path for the RKM service

UET/Redpoint.KubernetesManager/Services/DefaultAssetConfiguration.cs
=> Upgrade runc to 1.3.0

UET/Redpoint.KubernetesManager/Services/DefaultAssetConfiguration.cs
=> Upgrade etcd to 3.6.0

UET/Redpoint.KubernetesManager/Components/ControllerOnly/CoreDNSProvisioningComponent.cs
The CoreDNS chart uses /etc/resolv.conf as fallthrough, which doesn't work on systemd-based systems. Use 1.1.1.1 as the fallthrough server instead.
=> Use values file for CoreDNS deployment, fix fallthrough DNS servers

UET/Redpoint.CloudFramework.Tests/BatchingTests.cs, UET/Redpoint.CloudFramework.Tests/DatastoreRepositoryLayerTests.cs, UET/Redpoint.CloudFramework.Tests/GlobalRepositoryTests.cs, UET/Redpoint.CloudFramework.Tests/Infrastructure/CloudFrameworkCollectionFixture.cs, UET/Redpoint.CloudFramework.Tests/Models/BadModel.cs, UET/Redpoint.CloudFramework.Tests/Models/DefaultedBypassModel.cs, UET/Redpoint.CloudFramework.Tests/Models/DefaultedInvalidModel.cs, UET/Redpoint.CloudFramework.Tests/Models/DefaultedModel.cs, UET/Redpoint.CloudFramework.Tests/Models/EmbeddedEntityModel.cs, UET/Redpoint.CloudFramework.Tests/Models/GeoDenseModel.cs, UET/Redpoint.CloudFramework.Tests/Models/GeoSparseModel.cs, UET/Redpoint.CloudFramework.Tests/Models/TestModel.cs, UET/Redpoint.CloudFramework.Tests/RedisCacheRepositoryLayerTests.cs, UET/Redpoint.CloudFramework.Tests/RedisTestModel.cs, UET/Redpoint.CloudFramework.Tests/ValidatorTests.cs, UET/Redpoint.CloudFramework/Repository/Validation/DefaultModelValidator.cs, UET/Redpoint.CloudFramework/Repository/Validation/IModelValidator.cs, UET/Redpoint.CloudFramework/ServiceCollectionExtensions.cs
=> Add model validator API

.github/actions/download-artifact/action.yml, .github/actions/upload-artifact/action.yml, .github/workflows/uet.yml, UET/Lib/Helm/rkm/.helmignore, UET/Lib/Helm/rkm/Chart.yaml, UET/Lib/Helm/rkm/templates/calico/calico-config.yaml, UET/Lib/Helm/rkm/templates/calico/calico-kube-controllers-rbac.yaml, UET/Lib/Helm/rkm/templates/calico/calico-kube-controllers.yaml, UET/Lib/Helm/rkm/templates/calico/calico-node-rbac.yaml, UET/Lib/Helm/rkm/templates/calico/calico-node.yaml, UET/Lib/Helm/rkm/templates/calico/kdd-crds.yaml, UET/Lib/Helm/rkm/values.yaml
=> Package RKM components Helm chart

UET/uet/Commands/Cluster/ClusterRunContainerdCommand.cs
=> Restart kubelet if it was running when containerd first started

UET/Redpoint.Uet.Workspace/DefaultWorkspaceProvider.cs
If the Git repository URL contained credentials or query string parameters, this would result in the folder name being unique per build.
=> Fix Git workspace folder names being too unique

UET/Redpoint.Uefs.Daemon.Transactional.Executors/PullPackageTagTransactionExecutor.cs
=> Revert "Automatically retry connections to Docker registries on failure"
